services:
  postgres:
    image: postgres:16
    container_name: rental_room
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-kimthuy}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-kimthuy1997}
      POSTGRES_DB: ${DB_NAME:-rental_room}
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data

  nextjs-ui:  # <--- THIS WAS MISSING!
    image: ${DOCKER_HUB_USERNAME}/nextjs-api:latest
    container_name: rental_room_ui
    restart: unless-stopped
    ports:
      - "80:3000"  # Maps standard HTTP port 80 on AWS to Next.js port 3000
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-kimthuy}:${DB_PASSWORD:-kimthuy1997}@postgres:5432/${DB_NAME:-rental_room}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
        # AWS S3 Storage
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      
      # Google OAuth
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      
      # Resend SMTP Email Settings
      - EMAIL_SERVER_HOST=${EMAIL_SERVER_HOST}
      - EMAIL_SERVER_PORT=${EMAIL_SERVER_PORT}
      - EMAIL_SERVER_USER=${EMAIL_SERVER_USER}
      - EMAIL_SERVER_PASSWORD=${EMAIL_SERVER_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
    depends_on:
      - postgres

# version: '3.8'

# services:
#   local-postgres:
#     image: postgres:15-alpine
#     container_name: rental_room_postgres_local
#     environment:
#       POSTGRES_USER: kimthuy
#       POSTGRES_PASSWORD: kimthuy1997
#       POSTGRES_DB: rental_room
#     ports:
#       - "5432:5432"
#     volumes:
#       - local_postgres_data:/var/lib/postgresql/data
#     restart: unless-stopped

# volumes:
#   local_postgres_data: